Tensors are specialized data structures, that are very similar to arrays and matrices. In PyTorch, we use tensors to encode inputs and outputs of a model, as well as the model's parameters.

1. Similar to numpy's ndarrays
2. Can run on GPU's.
3. Tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data.
4. Tensors are optimized for automatic differentiation .


In [1]:
import torch
import numpy as np

In [2]:
# Creating tensors from data
data  = [[1,2],[3,4]]
x_data = torch.tensor(data)


In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
# Creating tensors from numpy arrays
np_array = np.array(data)
x_np = torch.from_numpy(np_array)


In [6]:
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
# Creating tensors from other tensors
# The new tensor retains the properties (shape, datatype) of of the argument tensor.

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n ")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 
 
Random Tensor: 
 tensor([[0.7360, 0.3301],
        [0.4790, 0.1812]]) 



In [9]:
# Shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.
shape  = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")




Random Tensor: 
 tensor([[0.7767, 0.5742, 0.6667],
        [0.4955, 0.4646, 0.4492]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
#Attributes of a Tensor
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Device tensor is stored on: {rand_tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [18]:
#Operations on Tensors
# We can perform a variety of operations on tensors.
"""
1. Arithmetic operations
2. Linear algebra
3. Matrix operations
"""
#Each of these operations can be run on CPU or Accelerators like GPU's.
#To run operations on the GPU, we need to use the .to method.
tensor = torch.rand(3,4)
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
tensor  = tensor.to(device)
x_data = x_data.to(device)
x_ones = x_ones.to(device)

print(f"First row: {tensor[0]} \n")
print(f"First Column: {tensor[:,0]} \n")
print(f"Last Column : {tensor[...,-1]} \n")

print(tensor)


First row: tensor([0.1664, 0.8581, 0.9006, 0.7826], device='cuda:0') 

First Column: tensor([0.1664, 0.5395, 0.0722], device='cuda:0') 

Last Column : tensor([0.7826, 0.4927, 0.4322], device='cuda:0') 

tensor([[0.1664, 0.8581, 0.9006, 0.7826],
        [0.5395, 0.8505, 0.9101, 0.4927],
        [0.0722, 0.8874, 0.2706, 0.4322]], device='cuda:0')


In [21]:
# Joining tensors : Sizes of tensors must match except in dimension 0. Expected size 4 but got size 2 for tensor number 1 in the list.

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.1664, 0.8581, 0.9006, 0.7826, 0.1664, 0.8581, 0.9006, 0.7826, 0.1664,
         0.8581, 0.9006, 0.7826],
        [0.5395, 0.8505, 0.9101, 0.4927, 0.5395, 0.8505, 0.9101, 0.4927, 0.5395,
         0.8505, 0.9101, 0.4927],
        [0.0722, 0.8874, 0.2706, 0.4322, 0.0722, 0.8874, 0.2706, 0.4322, 0.0722,
         0.8874, 0.2706, 0.4322]], device='cuda:0')


In [22]:
# Arithmetic operations
#Matrix Multiplication :  between 2 Tensors.
# tensor.T : transpose of the tensor.

y1 = tensor @ tensor.T # Matrix Multiplication : Dot Product of 2 Tensors.
y2 = tensor.matmul(tensor.T) 

y1, y2


(tensor([[2.1877, 2.0248, 1.3555],
         [2.0248, 2.0854, 1.2529],
         [1.3555, 1.2529, 1.0527]], device='cuda:0'),
 tensor([[2.1877, 2.0248, 1.3555],
         [2.0248, 2.0854, 1.2529],
         [1.3555, 1.2529, 1.0527]], device='cuda:0'))

In [27]:
y3 = torch.rand_like(y1)
# print(y3)
torch.matmul(tensor, tensor.T, out = y3)

y3

tensor([[2.1877, 2.0248, 1.3555],
        [2.0248, 2.0854, 1.2529],
        [1.3555, 1.2529, 1.0527]], device='cuda:0')

In [28]:
# Element-wise product : Multiplication of 2 Tensors.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z1, z2

(tensor([[0.0277, 0.7364, 0.8111, 0.6125],
         [0.2910, 0.7234, 0.8283, 0.2427],
         [0.0052, 0.7874, 0.0733, 0.1868]], device='cuda:0'),
 tensor([[0.0277, 0.7364, 0.8111, 0.6125],
         [0.2910, 0.7234, 0.8283, 0.2427],
         [0.0052, 0.7874, 0.0733, 0.1868]], device='cuda:0'))

In [29]:
z3 = torch.rand_like(tensor)

torch.mul(tensor, tensor, out = z3)
z3



tensor([[0.0277, 0.7364, 0.8111, 0.6125],
        [0.2910, 0.7234, 0.8283, 0.2427],
        [0.0052, 0.7874, 0.0733, 0.1868]], device='cuda:0')

In [30]:
# Single element tensors
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))


7.162923812866211 <class 'float'>


In [31]:
# In-place operations : Operations that store the result into the operand.
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.1664, 0.8581, 0.9006, 0.7826],
        [0.5395, 0.8505, 0.9101, 0.4927],
        [0.0722, 0.8874, 0.2706, 0.4322]], device='cuda:0') 

tensor([[5.1664, 5.8581, 5.9006, 5.7826],
        [5.5395, 5.8505, 5.9101, 5.4927],
        [5.0722, 5.8874, 5.2706, 5.4322]], device='cuda:0')


In [33]:
#Bridge with numpy

#Tensors to numpy arrays

t = torch.ones(5)
print(f"t: {t} \n")
n = t.numpy()
print(f"n : {n} \n")

#A change in the tensor reflects in the numpy array and vice versa..
t.add_(1)
print(f"t: {t} \n")
print(f"n : {n} \n")


t: tensor([1., 1., 1., 1., 1.]) 

n : [1. 1. 1. 1. 1.] 

t: tensor([2., 2., 2., 2., 2.]) 

n : [2. 2. 2. 2. 2.] 

