In [6]:
import numpy as np


In [7]:
arr = np.array([1,2,3])

print(arr)

[1 2 3]


In [8]:
def matrix_multiplication(A,B):
    """
    Multiply two matrices WITHOUT using np.matmul or @
    
    A: (m, n) matrix
    B: (n, p) matrix
    Returns: (m, p) matrix
    
    """
    
    #check dimentions - A's columns must equal B's rows

    assert A.shape[1] == B.shape[0], "INCOMPATIBLE DIMENSIONS"

    m,n = A.shape
    n,p = B.shape

    C = np.zeros((m,p))

    #code here
    #implement matrix multiplication - Triple Loop
    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i,j] += A[i,k] * B[k,j]
    
   
    return C
    

        



In [9]:
print("Test 1: Simple 2x2 matrices")
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [1, 2]])
result = matrix_multiplication(A, B)
print("Your result:")
print(result)
print("NumPy result:")
print(A @ B)
print("Match?", np.allclose(result, A @ B))

print("\nTest 2: Non-square matrices")
A = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3
B = np.array([[7, 8], [9, 10], [11, 12]])  # 3x2
result = matrix_multiplication(A, B)
print("Your result:")
print(result)
print("NumPy result:")
print(A @ B)
print("Match?", np.allclose(result, A @ B))

Test 1: Simple 2x2 matrices
Your result:
[[ 4.  7.]
 [10. 17.]]
NumPy result:
[[ 4  7]
 [10 17]]
Match? True

Test 2: Non-square matrices
Your result:
[[ 58.  64.]
 [139. 154.]]
NumPy result:
[[ 58  64]
 [139 154]]
Match? True
